# Generated by Django 5.0.7 on 2024-07-15 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rushee',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
