# Generated by Django 5.0.7 on 2024-07-17 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0003_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rushee',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='rushee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='rushee',
            name='last_name',
        ),
        migrations.AddField(
            model_name='rushee',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rushee',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rushee',
            name='discord',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rushee',
            name='dorm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rushee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='rushee',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rushee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rushee',
            name='status',
            field=models.CharField(choices=[('n', 'None'), ('a', 'Awaiting Bid'), ('b', 'Bid Delivered'), ('p', 'Pledged')], default='None', max_length=1),
        ),
    ]
