# Generated by Django 5.0.7 on 2024-07-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0007_discord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discord',
            name='userID',
        ),
        migrations.AlterField(
            model_name='discord',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
