# Generated by Django 5.0.7 on 2024-08-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0008_remove_discord_userid_alter_discord_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
