# Generated by Django 5.0.7 on 2024-08-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0009_signin'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='heard',
            field=models.CharField(default='dormspam', max_length=100),
            preserve_default=False,
        ),
    ]
