# Generated by Django 5.1.2 on 2024-10-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0010_signin_heard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
