# Generated by Django 5.1.2 on 2024-10-14 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0011_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rushee',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rush.status'),
        ),
    ]
