# Generated by Django 5.1.2 on 2024-10-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0012_alter_rushee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rushee',
            name='pronouns',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
